### ISSUE TITLE
Downloadable element: Icon display issue

### ISSUE THREAD

**Issue by mwolfensteinuwex** [oel-mediateam/droplets-for-canvas#1]
There's an issue with how the background of the icons is displaying on the downloadable elements. It appears as though it may be an issue related to padding, although I'm guessing it has to do with how Canvas is handling the CSS and that it would look fine outside of Canvas.

<img width="664" alt="downloadablesiconissue" src="https://cloud.githubusercontent.com/assets/8323077/13791587/dba70b8e-eabb-11e5-94b3-8347742fb786.png">

**Comment by Lin87** [comment]
Try clearing cache first and see if anything changed.

Ethan Lin
ethan.lin@uwex.edu<mailto:ethan.lin@uwex.edu>

On Mar 15, 2016, at 2:43 PM, Moses Wolfenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


There's an issue with how the background of the icons is displaying on the downloadable elements. It appears as though it may be an issue related to padding, although I'm guessing it has to do with how Canvas is handling the CSS and that it would look fine outside of Canvas.

[downloadablesiconissue]<https://cloud.githubusercontent.com/assets/8323077/13791587/dba70b8e-eabb-11e5-94b3-8347742fb786.png>

-

**Comment by mwolfensteinuwex** [comment]
Cleared the cache and it was still glitched.

**Comment by Lin87** [comment]
It's a font size thing. I adjust the size yesterday.

Ethan Lin
ethan.lin@uwex.edu<mailto:ethan.lin@uwex.edu>

On Mar 15, 2016, at 3:18 PM, Moses Wolfenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


Cleared the cache and it was still glitched.

-

**Comment by Lin87** [comment]
fixed.
