### ISSUE TITLE
unable to remove undesired copyright footer

### ISSUE THREAD

**Issue by ofloveandhate** [oel-mediateam/droplets-for-canvas#1]
In pages using Droplets, a non-removable footer is added asserting copyright over the content on the page.  See below image:

<img width="965" alt="Screen Shot 2022-02-22 at 14 05 30" src="https://user-images.githubusercontent.com/1388063/155210529-eaa6626a-ec81-4c8b-9290-eac7ac5f1adb.png">

What exactly is the board of regents asserting copyright over?  Droplets?  My content?  How can I disable this?  Is there a more appropriate or specific text to put there?

**Comment by ofloveandhate** [comment]
page source generating above image:

```
<div id="uws-droplets-page">
    <div class="callout info">
        <h4>Heading</h4>
        <p>Fred and George, who had been spying on the Slytherin team, had seen for themselves the speed of those new Nimbus Two Thousand and Ones.</p>
    </div>
</div>
```

**Comment by ofloveandhate** [comment]
this is on the uwec instance of Canvas, but it also happens locally when using droplets in the following markdown code:

```
<link href="https://media.uwex.edu/app/droplets_v3/css/droplets.css" rel="stylesheet">
<script href="https://media.uwex.edu/app/droplets_v3/script/droplets.js" type="test/javascript"></script>

<div id="uws-droplets-page">
  <!-- Droplets elements and components -->

## testing callouts

<div class="callout success" role="note"> <!-- add role="note" if supplement content and not aesthetic -->
  <h4>Heading</h4>
  <p>Fred and George, who had been spying on the Slytherin team, had seen for themselves the speed of those new Nimbus Two Thousand and Ones.</p>
</div>


</div>

```

**Comment by Lin87** [comment]
Add the “no-footer” class to the “#uws-droplets-page” div tag. https://media.uwex.edu/app/droplets_v3/layout.html#footer. The copyright is something the instructional designers here at UWEX want.

**Comment by ofloveandhate** [comment]
I think that on-by-default for that copyright footer is going to be a barrier to more widespread adoption of Droplets.  If people at non-UW institutions use Droplets, it's a lot to ask that *every person* use the code to stifle the incorrect-for-them copyright footer on *every page*.  Someone at another institution will forget, and it will cause (possibly legal) headaches.  

i wonder if there's another solution that involves patching the Droplets install or otherwise providing an instance-by-instance solution?  I think this is worth looking into.

**Comment by Lin87** [comment]
I will talk with the IDs and the Droplets group here. Personally, I find it weird too. But it is just something IDs want since version 1. Maybe they think differently now. I will ask them.

**Comment by Lin87** [comment]
Instructional Designers have no objections/comments about removing the copyright text in Droplets. The Droplets group is also in favor of removing it. So, it will be removed in the next upcoming update.

**Comment by Lin87** [comment]
Hi Silviana — Droplets version 3.2.5 is now available. This update removes the copyright text. No further action is needed for existing pages—it is automatically gone. I've sent the latest files to Tiffany for her to update in UWEC Canvas.
