### ISSUE TITLE
Spacing between lines changed with starter code

### ISSUE THREAD

**Issue by venitk** [oel-mediateam/droplets-for-canvas#2]
I noticed the starter code adjusts the space between the lines of the regular text ever so slightly, making it a little less comfortable to read online than Canvas's more roomy default spacing. It was uncomfortable enough that I decided not to use the droplets on the page I was working on because it was already pretty long. On a shorter page, I don't think it would bother me. 

I'm using Google Chrome, but not sure which version I was using when I noticed this (it was on April 20). I do usually keep Chrome up to date.

**Comment by Lin87** [comment]
Hello, sorry for the latest response. Your feedback has been implemented in the newest version of Droplets (v3.2.7). The font family, font size, font weight, and line spacing are now inherited from the LMS platform. They are not the same.
