### ISSUE TITLE
Accordion Works On Pages not Assignments

### ISSUE THREAD

**Issue by mckenziewest** [oel-mediateam/droplets-for-canvas#7]
This was tested on both Google Chrome and on Firefox on a Windows and Mac computer respectively.

In both cases, the Accordion component works as expected in a Page and does not work in an Assignment.

We are hoping to use collapsed accordions to provide hints for our assignments.

Test assignment with example code:
![image](https://github.com/uwex-learning-tech/droplets-v3/assets/20980506/c59074d0-5312-4897-bb5b-a9b9d46f5811)

Test page with example code:
![image](https://github.com/uwex-learning-tech/droplets-v3/assets/20980506/64874c0d-1112-4ee1-84ee-d9a9a6e9a5b8)

**Comment by owlboy** [comment]
Hello,

This and various other "interactive" components are not compatible with Quiz and Discussion pages/content areas.

This is due to limitations imposed by Canvas.

**Comment by mckenziewest** [comment]
alright, thanks for the update
